### ISSUE TITLE
Missing project property on CI

### ISSUE THREAD

**Issue by matshou** [yooksi/pz-zdoc#41]
[Github CI build](https://github.com/yooksi/pz-zdoc/runs/1842972231) failed due to missing project property.

`FAILURE`: Build failed with an exception.

* Where:
`Script '/home/runner/work/pz-zdoc/pz-zdoc/setup.gradle' line: 38`

* What went wrong:
A problem occurred evaluating script.
`> Unable to find local project property game.dir`

**Comment by yooksi** [comment]
This issue is still not properly resolved, see failed build [#77](https://github.com/yooksi/pz-zdoc/actions/runs/547935688).

**Comment by matshou** [comment]
This issue is still not properly resolved, see failed build [#77](https://github.com/yooksi/pz-zdoc/actions/runs/547935688).
